const SITE_URL = "https://calcbid.com";

// Public, indexable routes. Auth pages are intentionally excluded.
const routes = [
  { path: "/", priority: 1.0, changeFrequency: "weekly" },
  { path: "/calculators", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/paint-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/roofing-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/tile-flooring-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/deck-fence-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/hvac-btu-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/concrete-drywall-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/siding-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/pressure-washing-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/attic-insulation-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/gutter-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/fence-staining-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/window-replacement-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/epoxy-garage-floor-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/paver-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/water-heater-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/calculators/mulch-calculator", priority: 0.9, changeFrequency: "weekly" },
  { path: "/guides", priority: 0.7, changeFrequency: "weekly" },
  { path: "/guides/how-to-quote-a-painting-job", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/cost-to-paint-12x12-room", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/roof-replacement-cost-2026", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/paint-needed-2000-sqft-house", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/roofing-squares-chart", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/roof-pitch-multiplier-chart", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/painting-estimate-template", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/bundles-per-square", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/interior-painting-cost-per-sqft", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/quote-vs-estimate-vs-bid", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/how-to-quote-pressure-washing-job", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/how-to-bid-fence-staining-job", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/how-to-quote-siding-job", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/how-to-quote-tile-job", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/cost-to-replace-windows", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/mini-split-installation-cost", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/gutter-installation-cost", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/how-to-bid-concrete-slab", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/paver-installation-cost", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/lvp-flooring-cost", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/cost-to-epoxy-garage", priority: 0.7, changeFrequency: "monthly" },
  { path: "/guides/siding-cost-per-square-foot", priority: 0.7, changeFrequency: "monthly" },
  { path: "/about", priority: 0.5, changeFrequency: "monthly" },
  { path: "/contact", priority: 0.5, changeFrequency: "monthly" },
  { path: "/privacy", priority: 0.3, changeFrequency: "yearly" },
  { path: "/terms", priority: 0.3, changeFrequency: "yearly" },
  { path: "/quote", priority: 0.8, changeFrequency: "weekly" },
  { path: "/pricing", priority: 0.8, changeFrequency: "monthly" },
];

export default function sitemap() {
  const now = new Date();
  return routes.map((r) => ({
    url: `${SITE_URL}${r.path}`,
    lastModified: now,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}
