// Guide index — single source of truth for the /guides hub and sitemap.
export const guides = [
  {
    slug: "how-to-quote-a-painting-job",
    title: "How to Quote a Painting Job (Without Underbidding)",
    note: "The full walkthrough: measure, price materials, labor, markup — and send it.",
    keywords: ["how to quote a painting job", "painting quote", "how to bid a paint job"],
  },
  {
    slug: "cost-to-paint-12x12-room",
    title: "How Much Does It Cost to Paint a 12×12 Room?",
    note: "DIY vs pro pricing, gallons needed, and what moves the number.",
    keywords: ["cost to paint 12x12 room", "how much to paint a bedroom", "painting a room cost"],
  },
  {
    slug: "roof-replacement-cost-2026",
    title: "How Much Does a Roof Replacement Cost in 2026?",
    note: "Real US price ranges by material, what drives the quote up, and how to estimate it.",
    keywords: ["roof replacement cost", "how much does a new roof cost", "roof replacement cost 2026"],
  },
  {
    slug: "paint-needed-2000-sqft-house",
    title: "How Many Gallons of Paint for a 2,000 Sq Ft House?",
    note: "Interior, ceilings, trim, and exterior — the real gallon counts.",
    keywords: ["how many gallons of paint for 2000 sq ft house", "how much paint for a 2000 sq ft house"],
  },
  {
    slug: "roofing-squares-chart",
    title: "How Many Squares of Shingles Do I Need? (Chart)",
    note: "Roofing squares by home size, pitch-adjusted, plus the bundle math.",
    keywords: ["how many squares of shingles do i need", "roofing squares chart"],
  },
  {
    slug: "roof-pitch-multiplier-chart",
    title: "Roof Pitch Multiplier Chart (3/12–12/12)",
    note: "Footprint to true roof area for every common pitch.",
    keywords: ["roof pitch multiplier chart", "roof pitch multiplier"],
  },
  {
    slug: "painting-estimate-template",
    title: "Painting Estimate Template: What to Include (Free)",
    note: "The 8 parts every professional painting quote needs.",
    keywords: ["painting estimate template", "painting quote template", "free painting estimate template"],
  },
  {
    slug: "bundles-per-square",
    title: "How Many Bundles of Shingles Per Square?",
    note: "The standard 3-bundle count, the exceptions, and the order math.",
    keywords: ["how many bundles of shingles per square", "bundles per square roofing"],
  },
  {
    slug: "interior-painting-cost-per-sqft",
    title: "Interior Painting Cost Per Square Foot (2026)",
    note: "Real 2026 US price ranges per square foot — and what moves your number.",
    keywords: ["interior painting cost per square foot", "painting cost per square foot 2026"],
  },
  {
    slug: "quote-vs-estimate-vs-bid",
    title: "Quote vs Estimate vs Bid: What to Send When",
    note: "What each document means, when to send it, and which one protects you.",
    keywords: ["quote vs estimate vs bid", "difference between quote and estimate contractor"],
  },
  {
    slug: "how-to-quote-pressure-washing-job",
    title: "How to Quote a Pressure Washing Job (2026)",
    note: "Per-sq-ft rates by surface, minimum charges, and the walkthrough pros use.",
    keywords: ["how to quote a pressure washing job", "how to price pressure washing"],
  },
  {
    slug: "how-to-bid-fence-staining-job",
    title: "How to Bid a Fence Staining Job (2026)",
    note: "Per-linear-foot pricing, stain math, and the upsells that stack margin.",
    keywords: ["how to bid a fence staining job", "how to quote fence staining"],
  },
  {
    slug: "how-to-quote-siding-job",
    title: "How to Quote a Siding Job (2026 Guide)",
    note: "Squares, material tiers, trim, and tear-off — the bid that wins.",
    keywords: ["how to quote a siding job", "how to bid siding"],
  },
  {
    slug: "how-to-quote-tile-job",
    title: "How to Quote a Tile Installation Job",
    note: "Setting materials, labor per sq ft, and the extras that eat margin.",
    keywords: ["how to quote a tile installation job", "how to bid tile work"],
  },
  {
    slug: "cost-to-replace-windows",
    title: "Cost to Replace All Windows in a House (2026)",
    note: "Per-window prices by material and whole-house ranges.",
    keywords: ["cost to replace all windows in a house", "how much does it cost to replace windows"],
  },
  {
    slug: "mini-split-installation-cost",
    title: "Mini Split Installation Cost in 2026",
    note: "Per-zone pricing, what drives the bid, and when it beats central air.",
    keywords: ["mini split installation cost", "how much does a mini split cost"],
  },
  {
    slug: "gutter-installation-cost",
    title: "Gutter Installation Cost Per Linear Foot (2026)",
    note: "Aluminum, steel, and copper pricing plus downspouts and guards.",
    keywords: ["gutter installation cost per linear foot", "how much do gutters cost"],
  },
  {
    slug: "how-to-bid-concrete-slab",
    title: "How to Bid a Concrete Slab Job (2026)",
    note: "Yardage, forming, rebar, finishing, and site conditions.",
    keywords: ["how to bid a concrete slab job", "how to quote concrete work"],
  },
  {
    slug: "paver-installation-cost",
    title: "Paver Installation Cost Per Square Foot (2026)",
    note: "Materials, base, and labor for patios, walkways, and driveways.",
    keywords: ["paver installation cost per square foot", "how much do pavers cost"],
  },
  {
    slug: "lvp-flooring-cost",
    title: "LVP Flooring Installation Cost Per Sq Ft (2026)",
    note: "Material grades, labor, and the prep work that decides the bid.",
    keywords: ["lvp flooring installation cost per square foot", "luxury vinyl plank installation cost"],
  },
  {
    slug: "cost-to-epoxy-garage",
    title: "Cost to Epoxy a 2-Car Garage in 2026",
    note: "DIY kit math vs pro pricing — and what drives the bid.",
    keywords: ["cost to epoxy a 2 car garage", "how much does it cost to epoxy a garage floor"],
  },
  {
    slug: "siding-cost-per-square-foot",
    title: "Siding Installation Cost Per Square Foot (2026)",
    note: "Vinyl, fiber cement, wood, and metal pricing plus tear-off.",
    keywords: ["siding installation cost per square foot", "how much does siding cost"],
  },
];
